/* Autogenerated file. Do not edit manually. */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import type { IFaucet } from './IFaucet';

export class IFaucet__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): IFaucet {
    return new Contract(address, _abi, signerOrProvider) as IFaucet;
  }
}

const _abi = [
  {
    inputs: [],
    name: 'mintAll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'lastMintTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
];
